{% set name = "oracledb" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oracledb-{{ version }}.tar.gz
  sha256: 96ba508f783892c7ca648f268acbcb8a4a9c8037c7dd4a509f05f2c89d6231be

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - pip
  run:
    - python
    - cryptography >=3.2.1

test:
  imports:
    - oracledb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://oracle.github.io/python-oracledb
  summary: Python interface to Oracle Database
  dev_url: https://github.com/oracle/python-oracledb
  doc_url: https://python-oracledb.readthedocs.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - xylar
