{% set name = "oracledb" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oracledb-{{ version }}.tar.gz
  sha256: 58b86511d9e149041fd49df1baa271fc7be090fc0736130dd520afbc7e1d87a9

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - pip
    - setuptools >=77.0.0
  run:
    - python
    - cryptography >=3.2.1

test:
  imports:
    - oracledb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://oracle.github.io/python-oracledb
  summary: Python interface to Oracle Database
  dev_url: https://github.com/oracle/python-oracledb
  doc_url: https://python-oracledb.readthedocs.io/en/latest/
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - NOTICE.txt

extra:
  recipe-maintainers:
    - xylar
